name: Android CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  ui-tests:
    strategy:
      matrix:
        api-level: [28]
        target: [default]
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v3.6.0
      with:
        distribution: 'temurin'
        java-version: 11
        cache: 'gradle'
    - name: Install the Emulator
      run: |
        chmod +x ./scripts/RunAppiumServer.sh
        ./scripts/RunAppiumServer.sh
      shell: bash   
    - name: Run Appium Testss
      uses: reactivecircus/android-emulator-runner@v2.27.0
      with:
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        arch: x86_64
        profile: Nexus 6
        script: ./gradlew test --info
    - name: Upload test report
      uses: actions/upload-artifact@v2
      with:
        name: unit_test_report
        path: /Users/runner/work/Gusi/
        
